name: crates

concurrency:
  cancel-in-progress: false
  group: ${{ github.workflow }}-${{ github.ref }}

env:
  BASENAME: ${{ github.event.repository.name }}
  CARGO_TERM_COLOR: always

on:
  release:
    types: [ published ]
  repository_dispatch:
    types: [ crates-io ]
  workflow_dispatch:

jobs:
  base:
    env:
      CRATE_NAME: ${{ github.event.repository.name }}-${{ matrix.features }}
    name: Publish Core Crates
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        features: [ core ]
    steps:
      - uses: actions/checkout@v4
      - name: publish (${{ env.CRATE_NAME }})
        run: cargo publish --all-features -v -p ${{ env.CRATE_NAME }} --token ${{ secrets.CARGO_REGISTRY_TOKEN }}
  sdk:
    name: Publish SDK (${{ github.event.repository.name }})
    needs: base
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cargo publish --all-features -v -p ${{ env.BASENAME }} --token ${{ secrets.CARGO_REGISTRY_TOKEN }}